<?php

use Drupal\Core\Theme\ThemeManagerInterface;

/**
 * Implements hook_theme().
 */
function custom_contact_theme($existing, $type, $theme, $path) {
  return [
    'custom_contact_form_page' => [
      'variables' => ['form' => NULL],
      'template' => 'custom-contact-form-page',  // correspond au nom du fichier twig sans .html.twig
      'template_path' => __DIR__ . '/templates',
    ],
  ];
}
